In [483]:
# Data Science Assignment 3
# Problem 2: German Credit
# German Credit Dataset (72 Points)
#Preprocessing
#1.1
'''
I have no idea whats going on here

[8 pts] Drop the 3 columns that contribute the least to the dataset. 
These would be the columns with the highest number of non-zero 'none' values. 
Break ties by going left to right in columns. (Your code should be generalizable to drop n columns, 
but for the rest of the analysis, you can call your code for n=3.)

'''
import csv
import pandas as pd
def preprocessing(file):
    count = 0
    with open(file) as openedFile:
        df = pd.read_csv(openedFile)
#     return df
#         next(df)
        x=0
        for row in df:
            dic = {}
#             print(len(df[row].value_counts()))
            dic = df[row].value_counts()
#             print(dic)
#             for col in row:
#                 if col == "none":
#                     print(col)
#                 print(col)
#             print(row)
# preprocessing("GermanCredit.csv")

In [484]:
#1.2
'''

Hardcoding this so should be worked on if you can figure it out but Done

[4 pts] Certain values in some of the columns contain unnecessary apostrophes (â€˜). Remove the apostrophes.

'''
import csv
import pandas as pd
def removeApost(file): 
    with open(file) as openedFile:
        dfpd = pd.read_csv(openedFile)

        dfpd['checking_status'] = dfpd['checking_status'].str.replace("'","")
        dfpd['credit_history'] = dfpd['credit_history'].str.replace("'","")
        dfpd['purpose'] = dfpd['purpose'].str.replace("'","")
        dfpd['savings_status'] = dfpd['savings_status'].str.replace("'","")
        dfpd['employment'] = dfpd['employment'].str.replace("'","")
        dfpd['personal_status'] = dfpd['personal_status'].str.replace("'","")
        dfpd['other_parties'] = dfpd['other_parties'].str.replace("'","")
        dfpd['property_magnitude'] = dfpd['property_magnitude'].str.replace("'","")
        dfpd['other_payment_plans'] = dfpd['other_payment_plans'].str.replace("'","")
        dfpd['housing'] = dfpd['housing'].str.replace("'","")
        dfpd['job'] = dfpd['job'].str.replace("'","")
        dfpd['own_telephone'] = dfpd['own_telephone'].str.replace("'","")
        dfpd['foreign_worker'] = dfpd['foreign_worker'].str.replace("'","")
        dfpd['class'] = dfpd['class'].str.replace("'","")

        return dfpd

# removeApost("GermanCredit.csv")

In [486]:
#1.3 
'''
Done

[5 pts] The checking_status column has values in 4 categories: 
'no checking', '<0', '0<=X<200', and '>=200'. Change these to 'No Checking', 
'Low', 'Medium', and 'High' respectively.

'''
import csv 
import pandas as pd
def checkingStatus(file):
    with open(file) as openedFile:
        dfpd = pd.read_csv(openedFile)
        dfpd['checking_status'] = dfpd['checking_status'].str.replace("'","")
        dfpd['checking_status'] = dfpd['checking_status'].str.replace("no checking","No Checking")
        dfpd['checking_status'] = dfpd['checking_status'].str.replace("<0","Low")
        dfpd['checking_status'] = dfpd['checking_status'].str.replace("0<=X<200","Medium")
        dfpd['checking_status'] = dfpd['checking_status'].str.replace(">=200","High")
        
        return dfpd

# checkingStatus("GermanCredit.csv")

In [487]:
#1.4
'''
Done

[5 pts] The savings_status column has values in 4 categories: 'no known savings', 
'<100', '100<=X<500', '500<=X<1000', and '>=1000'. Change these to 'No Savings', 'Low', 
'Medium', 'High', and 'High' respectively. (Yes, the last two are both 'High').

'''
import csv
import pandas as pd
def savingStatus(file):
    with open(file) as openedFile:
        df = csv.reader(openedFile)
        dfpd = pd.read_csv(openedFile)
        
        dfpd['savings_status'] = dfpd['savings_status'].str.replace("'","")
        dfpd['savings_status'] = dfpd['savings_status'].str.replace("no known savings","No Savings")
        dfpd['savings_status'] = dfpd['savings_status'].str.replace("<100","Low")
        dfpd['savings_status'] = dfpd['savings_status'].str.replace("100<=X<500","Medium")
        dfpd['savings_status'] = dfpd['savings_status'].str.replace("500<=X<1000","High")
        dfpd['savings_status'] = dfpd['savings_status'].str.replace(">=1000","High")
        
        return dfpd
        
# savingStatus("GermanCredit.csv")

In [488]:
#1.5
'''
Done

[4 pts] Change class column values from 'good' to '1' and 'bad' to '0'

'''
import csv 
import pandas as pd
def changingClass(file):
    with open(file) as openedFile:
        df = csv.reader(openedFile)
        dfpd = pd.read_csv(openedFile)
        dfpd['class'] = dfpd['class'].str.replace("'","")
        dfpd['class'] = dfpd['class'].str.replace("good","1")
        dfpd['class'] = dfpd['class'].str.replace("bad","0")

    return dfpd
            
# changingClass("GermanCredit.csv")

In [489]:
#1.6
'''
Done

[5 pts] Change the employment column value 'unemployed' to 'Unemployed', 
and for the others, change to 'Amateur', 'Professional', 'Experienced' and 'Expert', depending on year range.

'''
import csv 
import pandas as pd
def changingEmployment(file):
    with open(file) as openedFile:
        dfpd = pd.read_csv(openedFile)
        dfpd['employment'] = dfpd['employment'].str.replace("'","")
        dfpd['employment'] = dfpd['employment'].str.replace("unemployed","Unemployed")
        dfpd['employment'] = dfpd['employment'].str.replace("<1","Amateur")
        dfpd['employment'] = dfpd['employment'].str.replace("1<=X<4","Professional")
        dfpd['employment'] = dfpd['employment'].str.replace("4<=X<7","Experienced")
        dfpd['employment'] = dfpd['employment'].str.replace(">=7","Expert")

        return (dfpd)
    
# changingEmployment("GermanCredit.csv")

In [490]:
#Analysis (17 pts)
# 2.1a
'''
Done

[3 pts] Get the count of each category of foreign workers (yes and no) for each class of credit (good and bad).

'''
import csv
import pandas as pd
def countForeignWorkers(file):
    with open(file) as openedFile:
        dfpd = pd.read_csv(openedFile)
        cross = pd.crosstab(dfpd.foreign_worker, dfpd['class'])
        return cross
    
# countForeignWorkers("GermanCredit.csv")

In [491]:
#2.1b
'''
Done

[2 pts] Similarly, get the count of each category of employment for each category of saving_status.

'''
import csv
import pandas as pd
def countEmployment(file):
    with open(file) as openedFile:
        dfpd = pd.read_csv(openedFile)
        cross = pd.crosstab(dfpd.employment, dfpd.savings_status)
        return cross
    
# countEmployment("GermanCredit.csv")

In [493]:
#2.2
'''
Done

[4 pts] Find the average credit_amount of single males that have 4<=X<7 years of employment. You can leave the raw result as is, no need for rounding.

'''
import csv
import pandas as pd
def avgCreditEmployment(file):
    with open(file) as openedFile:
        dfpd = pd.DataFrame(openedFile)
        count = 0
        creditSum = 0
        for row in dfpd.iterrows():
            for val in row[1]:
                x = val.split(",")
                if x[8] == "'male single'" and x[6] == "'4<=X<7'":
                    num = int(x[4])
                    creditSum = creditSum + num
                    count = count + 1
                else:
                    continue
        return creditSum/count

# avgCreditEmployment("GermanCredit.csv")

In [495]:
#2.3
'''
Done

[4 pts] Find the average credit duration for each of the job types. You can leave the raw result as is, no need for rounding.

'''
import csv
import pandas as pd
def avgCreditEmployment(file):
    with open(file) as openedFile:
        dfpd = pd.DataFrame(openedFile)
        skilledCount = 0
        skilledCreditSum = 0
        urCount = 0
        urCreditSum = 0
        hqCount = 0
        hqCreditSum = 0
        uuCount = 0
        uuCreditSum = 0
        for row in dfpd.iterrows():
            for val in row[1]:
                x = val.split(",")
                if x[16] == "skilled":
                    skilled = int(x[1])
                    skilledCount = skilledCount + 1
                    skilledCreditSum = skilledCreditSum + skilled
                elif x[16] == "'unskilled resident'":
                    ur = int(x[1])
                    urCount = urCount + 1
                    urCreditSum = urCreditSum + ur
                elif x[16] == "'high qualif/self emp/mgmt'":
                    hq = int(x[1])
                    hqCount = hqCount + 1
                    hqCreditSum = hqCreditSum + hq
                elif x[16] == "'unemp/unskilled non res'":
                    uu = int(x[1])
                    uuCount = uuCount + 1
                    uuCreditSum = uuCreditSum + uu
                else:
                    continue
        print("Skilled:",(skilledCreditSum/skilledCount))
        print("Unskilled Resident:",(urCreditSum/urCount))
        print("High Qualif/Self Emp/Mgmt:",(hqCreditSum/hqCount))
        print("Unemp/Unskilled Non Res:",(uuCreditSum/uuCount))

# avgCreditEmployment("GermanCredit.csv")

In [498]:
#2.4
'''
Done

[4 pts] For the purpose 'education', what is the most common checking_status and savings_status? Your code should print:
    Most common checking status: ...
    Most common savings status: ...

'''
import csv
import pandas as pd
def educationStatus(file):
    with open(file) as openedFile:
        dfpd = pd.DataFrame(openedFile)
        cCount1 = 0
        cCount2 = 0
        cCount3 = 0
        cCount4 = 0
        
        sCount1 = 0
        sCount2 = 0
        sCount3 = 0
        sCount4 = 0
        sCount5 = 0
        
        cStatus1 = "no checking"
        cStatus2 = "<0"
        cStatus3 = "0<=X<200"
        cStatus4 = ">=200"  
        
        sStatus1 = "no known savings"
        sStatus2 = "<100"
        sStatus3 = "100<=X<500"
        sStatus4 = "500<=X<1000"
        sStatus5 = ">=1000"
        
        for row in dfpd.iterrows():
            for val in row[1]:
                x = val.split(",")
                if x[3] == "education":
                    if x[0] == "'no checking'":
                        cCount1 = cCount1 + 1
                    elif x[0] == "'<0'":
                        cCount2 = cCount1 + 1
                    elif x[0] == "'0<=X<200'":
                        cCount3 = cCount1 + 1
                    elif x[0] == "'>=200'":
                        cCount4 = cCount1 + 1
                    if x[5] == "'no known savings'":
                        sCount1 = sCount1 + 1
                    elif x[5] == "'<100'":
                        sCount2 = sCount2 + 1
                    elif x[5] == "'100<=X<500'":
                        sCount3 = sCount3 + 1
                    elif x[5] == "'500<=X<1000'":
                        sCount4 = sCount4 + 1
                    elif x[5] == "'>=1000'":
                        sCount5 = sCount5 + 1
#         print(cCount1,cCount2,cCount3,cCount4,sCount1,sCount2,sCount3,sCount4,sCount5)    
        if max(cCount1, cCount2, cCount3, cCount4) == cCount1:
            checkingResult = cStatus1
        elif max(cCount1, cCount2, cCount3, cCount4) == cCount2:
            checkingResult = cStatus2
        elif max(cCount1, cCount2, cCount3, cCount4) == cCount3:
            checkingResult = cStatus3
        elif max(cCount1, cCount2, cCount3, cCount4) == cCount4:
            checkingResult = cStatus4
            
        if max(sCount1, sCount2, sCount3, sCount4, sCount5) == sCount1:
            savingsResult = sStatus1
        elif max(sCount1, sCount2, sCount3, sCount4, sCount5) == sCount2:
            savingsResult = sStatus2
        elif max(sCount1, sCount2, sCount3, sCount4, sCount5) == sCount3:
            savingsResult = sStatus3
        elif max(sCount1, sCount2, sCount3, sCount4, sCount5) == sCount4:
            savingsResult = sStatus4
        elif max(sCount1, sCount2, sCount3, sCount4, sCount5) == sCount5:
            savingsResult = sStatus5
        
        print("Most common checking status:", checkingResult)       
        print("Most common savings status:", savingsResult) 
        
# educationStatus("GermanCredit.csv")

In [545]:
#Visualization (24 pts)
#3.1
'''
[9 pts] Plot subplots of two histograms: one with savings_status on the x-axis and personal_status as different colors, and another with checking_status on the x-axis and personal_status as different colors.

'''
import csv
import pandas as pd
import matplotlib.pyplot as plt
def createHist(file):
    with open(file) as openedFile:
        dfpd = pd.read_csv(openedFile)
        dflux = pd.DataFrame(dict(rate=np.random.randn(10000)))
        dflux2 = pd.DataFrame(dict(rate=np.random.randn(10000)))

        fig, axes = plt.subplots(1, 2)

        dflux.hist('rate', bins=100, ax=axes[0])
        dflux2.hist('rate', bins=100, ax=axes[1])
        
#         return dfpd
#         ocp = dfpd.checking_status, dfpd.savings_status
#         ic_vals = dfpd['checking_status'].value_counts()
#         is_vals = dfpd['savings_status'].value_counts()
#         plt.bar(is_vals.index, is_vals.values)
#         plt.bar(ic_vals.index, ic_vals.values)
#         plt.xlabel("Savings Status")
#         plt.ylabel("Personal Status")

# createHist("GermanCredit.csv")

In [571]:
#3.2
'''
[9 pts] For people having credit_amount more than 4000, plot a bar graph which maps property_magnitude (x-axis) to the average customer age for that magnitude (y-axis).

'''

'\n[9 pts] For people having credit_amount more than 4000, plot a bar graph which maps property_magnitude (x-axis) to the average customer age for that magnitude (y-axis).\n\n'

In [501]:
#3.3
'''
[6 pts] For people with a "High" savings_status and age above 40, use subplots to plot the following pie charts:
Personal status
Credit history
Job

'''

'\n[6 pts] For people with a "High" savings_status and age above 40, use subplots to plot the following pie charts:\nPersonal status\nCredit history\nJob\n\n'

In [572]:
#test and sratch code
import csv
import pandas as pd
import numpy as np
def testFunction(file):
    with open(file) as openedFile:
        dfpd = pd.read_csv(openedFile)
        df = []
        for val in dfpd.credit_amount:
            if val > 4000:
                df.append(val)
#         return df
        newdf = [df, dfpd.property_magnitude, dfpd.age]
    return (pd.DataFrame(newdf))
    
testFunction("GermanCredit.csv")

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,5951,7882,4870,9055,6948,5234,4308,8072,12579,6836,...,None,None,None,None,None,None,None,None,None,None
1,'real estate','real estate','real estate','life insurance','no known property','no known property','life insurance',car,'real estate',car,...,'life insurance',car,car,'life insurance',car,'real estate','life insurance',car,'no known property',car
2,67,22,49,45,53,35,53,35,61,28,...,37,34,23,30,50,31,40,38,23,27